version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: vibe_postgres
    environment:
      POSTGRES_USER: vibe_user
      POSTGRES_PASSWORD: vibe_password
      POSTGRES_DB: vibe_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vibe_user -d vibe_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vibe_backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://vibe_user:vibe_password@postgres:5432/vibe_db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-true}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
